### ISSUE TITLE
Unable scheduleing export job. Exporter seems down.

### ISSUE THREAD

**Issue by worm-emoji** [typerandom/validator#31]
Hey, I hate to bring this here but I have sent email to Userapp support with no response. This seems like the only way to reach you. I have an app that is run on Userapp and I didn't find out until recently that Userapp is no longer being actively developed. I want to export all of my user data out of userapp, but the exporter is down. Could you fix the exporter so I can migrate my app away from your service? Thank  you. Again, I hate to reach you like this but I think it's irresponsible the way UserApp is operated currently with no indication that it is not actively developed or supported.

![broken exporter noooooo](https://cloud.githubusercontent.com/assets/1691179/7786088/457c2b94-0169-11e5-8a8c-285ed5e31272.png)

**Comment by rorheden** [comment]
Hi Luke,

Yes, this is definitely the wrong forum for such a question. But I'm really sorry that you needed to use that in order to get a hold of us. The UserApp SaaS is currently on hold since we're developing an open-source version.

And since we're not charging anyone, we're neither giving anyone support (since we get so much).

But I fully agree with you. The current situation is not something that is holding. And we really do need to update the website so that no one signs up without knowing the current status of our SaaS product.

Anyhow.

I was unable to find your account, so please send me an email to **robin.orheden {at} userapp {dot} io** with your AppId and email of your account, and I'll run a full data export (with passwords) for you.

Thanks,

Robin

(P.S. Since this issue is unrelated to this repo I'm closing it. Please don't answer here, but instead email me on the address provided above.)
